name: Geckodesign
favicon: null
layout_spectrum: 1
typography_spectrum: 0.03846
title: Gecko.design
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#939498'
    - '#030202'
    - '#ABCF38'
    - '#FAF102'
  brandStrength: 1
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
